export interface StockEntry {
  ticker: string;
  name: string;
  sector: string;
  industry: string;
  exchange: string;
}

// [ticker, name, sector, industry, exchange]
type Row = [string, string, string, string, string];

const rows: Row[] = [
  // ── Information Technology ──────────────────────────────────────────────
  ['AAPL','Apple Inc.','Technology','Consumer Electronics','NASDAQ'],
  ['MSFT','Microsoft Corp.','Technology','Software—Infrastructure','NASDAQ'],
  ['NVDA','NVIDIA Corp.','Technology','Semiconductors','NASDAQ'],
  ['AVGO','Broadcom Inc.','Technology','Semiconductors','NASDAQ'],
  ['AMD','Advanced Micro Devices','Technology','Semiconductors','NASDAQ'],
  ['ADBE','Adobe Inc.','Technology','Software—Application','NASDAQ'],
  ['QCOM','Qualcomm Inc.','Technology','Semiconductors','NASDAQ'],
  ['CSCO','Cisco Systems Inc.','Technology','Communication Equipment','NASDAQ'],
  ['INTC','Intel Corp.','Technology','Semiconductors','NASDAQ'],
  ['INTU','Intuit Inc.','Technology','Software—Application','NASDAQ'],
  ['AMAT','Applied Materials Inc.','Technology','Semiconductor Equipment','NASDAQ'],
  ['LRCX','Lam Research Corp.','Technology','Semiconductor Equipment','NASDAQ'],
  ['MU','Micron Technology Inc.','Technology','Semiconductors','NASDAQ'],
  ['SNPS','Synopsys Inc.','Technology','Software—Application','NASDAQ'],
  ['KLAC','KLA Corp.','Technology','Semiconductor Equipment','NASDAQ'],
  ['CDNS','Cadence Design Systems','Technology','Software—Application','NASDAQ'],
  ['ADI','Analog Devices Inc.','Technology','Semiconductors','NASDAQ'],
  ['MCHP','Microchip Technology','Technology','Semiconductors','NASDAQ'],
  ['NXPI','NXP Semiconductors','Technology','Semiconductors','NASDAQ'],
  ['ON','ON Semiconductor','Technology','Semiconductors','NASDAQ'],
  ['PANW','Palo Alto Networks','Technology','Software—Infrastructure','NASDAQ'],
  ['CRWD','CrowdStrike Holdings','Technology','Software—Infrastructure','NASDAQ'],
  ['FTNT','Fortinet Inc.','Technology','Software—Infrastructure','NASDAQ'],
  ['ACN','Accenture PLC','Technology','Information Technology Services','NYSE'],
  ['IBM','International Business Machines','Technology','Information Technology Services','NYSE'],
  ['ORCL','Oracle Corp.','Technology','Software—Infrastructure','NYSE'],
  ['CRM','Salesforce Inc.','Technology','Software—Application','NYSE'],
  ['IT','Gartner Inc.','Technology','Information Technology Services','NYSE'],
  ['CTSH','Cognizant Technology Solutions','Technology','Information Technology Services','NASDAQ'],
  ['HPE','Hewlett Packard Enterprise','Technology','Computer Hardware','NYSE'],
  ['DELL','Dell Technologies','Technology','Computer Hardware','NYSE'],
  ['WDC','Western Digital Corp.','Technology','Computer Hardware','NASDAQ'],
  ['STX','Seagate Technology','Technology','Computer Hardware','NASDAQ'],
  ['NTAP','NetApp Inc.','Technology','Computer Hardware','NASDAQ'],
  ['KEYS','Keysight Technologies','Technology','Scientific & Technical Instruments','NYSE'],
  ['ANSS','ANSYS Inc.','Technology','Software—Application','NASDAQ'],
  ['VRSN','VeriSign Inc.','Technology','Software—Infrastructure','NASDAQ'],
  ['AKAM','Akamai Technologies','Technology','Software—Infrastructure','NASDAQ'],
  ['FSLR','First Solar Inc.','Technology','Solar','NASDAQ'],
  ['ENPH','Enphase Energy Inc.','Technology','Solar','NASDAQ'],
  ['GEN','Gen Digital Inc.','Technology','Software—Infrastructure','NASDAQ'],
  ['PTC','PTC Inc.','Technology','Software—Application','NASDAQ'],
  ['TYL','Tyler Technologies','Technology','Software—Application','NYSE'],
  ['JKHY','Jack Henry & Associates','Technology','Software—Application','NASDAQ'],
  ['FFIV','F5 Inc.','Technology','Software—Infrastructure','NASDAQ'],
  ['ADP','Automatic Data Processing','Technology','Software—Application','NASDAQ'],
  ['PAYX','Paychex Inc.','Technology','Software—Application','NASDAQ'],
  ['WDAY','Workday Inc.','Technology','Software—Application','NASDAQ'],
  ['NOW','ServiceNow Inc.','Technology','Software—Application','NYSE'],
  ['SNOW','Snowflake Inc.','Technology','Software—Application','NYSE'],
  // ── Communication Services ──────────────────────────────────────────────
  ['META','Meta Platforms Inc.','Communication Services','Internet Content & Information','NASDAQ'],
  ['GOOGL','Alphabet Inc. Class A','Communication Services','Internet Content & Information','NASDAQ'],
  ['GOOG','Alphabet Inc. Class C','Communication Services','Internet Content & Information','NASDAQ'],
  ['NFLX','Netflix Inc.','Communication Services','Entertainment','NASDAQ'],
  ['DIS','The Walt Disney Co.','Communication Services','Entertainment','NYSE'],
  ['CMCSA','Comcast Corp.','Communication Services','Telecom Services','NASDAQ'],
  ['T','AT&T Inc.','Communication Services','Telecom Services','NYSE'],
  ['VZ','Verizon Communications','Communication Services','Telecom Services','NYSE'],
  ['TMUS','T-Mobile US Inc.','Communication Services','Telecom Services','NASDAQ'],
  ['WBD','Warner Bros. Discovery','Communication Services','Entertainment','NASDAQ'],
  ['PARA','Paramount Global','Communication Services','Entertainment','NASDAQ'],
  ['FOXA','Fox Corp. Class A','Communication Services','Entertainment','NASDAQ'],
  ['OMC','Omnicom Group','Communication Services','Advertising Agencies','NYSE'],
  ['IPG','Interpublic Group','Communication Services','Advertising Agencies','NYSE'],
  ['LYV','Live Nation Entertainment','Communication Services','Entertainment','NYSE'],
  ['EA','Electronic Arts','Communication Services','Electronic Gaming & Multimedia','NASDAQ'],
  ['TTWO','Take-Two Interactive','Communication Services','Electronic Gaming & Multimedia','NASDAQ'],
  // ── Consumer Discretionary ─────────────────────────────────────────────
  ['AMZN','Amazon.com Inc.','Consumer Discretionary','Internet Retail','NASDAQ'],
  ['TSLA','Tesla Inc.','Consumer Discretionary','Auto Manufacturers','NASDAQ'],
  ['HD','The Home Depot Inc.','Consumer Discretionary','Home Improvement Retail','NYSE'],
  ['MCD','McDonald\'s Corp.','Consumer Discretionary','Restaurants','NYSE'],
  ['NKE','NIKE Inc.','Consumer Discretionary','Footwear & Accessories','NYSE'],
  ['LOW','Lowe\'s Companies','Consumer Discretionary','Home Improvement Retail','NYSE'],
  ['SBUX','Starbucks Corp.','Consumer Discretionary','Restaurants','NASDAQ'],
  ['TJX','TJX Companies','Consumer Discretionary','Apparel Retail','NYSE'],
  ['BKNG','Booking Holdings','Consumer Discretionary','Travel Services','NASDAQ'],
  ['ORLY','O\'Reilly Automotive','Consumer Discretionary','Specialty Retail','NASDAQ'],
  ['AZO','AutoZone Inc.','Consumer Discretionary','Specialty Retail','NYSE'],
  ['ROST','Ross Stores Inc.','Consumer Discretionary','Apparel Retail','NASDAQ'],
  ['EBAY','eBay Inc.','Consumer Discretionary','Internet Retail','NASDAQ'],
  ['GM','General Motors Co.','Consumer Discretionary','Auto Manufacturers','NYSE'],
  ['F','Ford Motor Co.','Consumer Discretionary','Auto Manufacturers','NYSE'],
  ['CMG','Chipotle Mexican Grill','Consumer Discretionary','Restaurants','NYSE'],
  ['YUM','Yum! Brands Inc.','Consumer Discretionary','Restaurants','NYSE'],
  ['DRI','Darden Restaurants','Consumer Discretionary','Restaurants','NYSE'],
  ['HLT','Hilton Worldwide Holdings','Consumer Discretionary','Lodging','NYSE'],
  ['MAR','Marriott International','Consumer Discretionary','Lodging','NASDAQ'],
  ['CCL','Carnival Corp.','Consumer Discretionary','Travel Services','NYSE'],
  ['RCL','Royal Caribbean Cruises','Consumer Discretionary','Travel Services','NYSE'],
  ['EXPE','Expedia Group','Consumer Discretionary','Travel Services','NASDAQ'],
  ['ABNB','Airbnb Inc.','Consumer Discretionary','Travel Services','NASDAQ'],
  ['DKNG','DraftKings Inc.','Consumer Discretionary','Gambling','NASDAQ'],
  ['MGM','MGM Resorts International','Consumer Discretionary','Resorts & Casinos','NYSE'],
  ['WYNN','Wynn Resorts Ltd.','Consumer Discretionary','Resorts & Casinos','NASDAQ'],
  ['LVS','Las Vegas Sands Corp.','Consumer Discretionary','Resorts & Casinos','NYSE'],
  ['PHM','PulteGroup Inc.','Consumer Discretionary','Residential Construction','NYSE'],
  ['DHI','D.R. Horton Inc.','Consumer Discretionary','Residential Construction','NYSE'],
  ['LEN','Lennar Corp.','Consumer Discretionary','Residential Construction','NYSE'],
  ['BBY','Best Buy Co.','Consumer Discretionary','Specialty Retail','NYSE'],
  ['MELI','MercadoLibre Inc.','Consumer Discretionary','Internet Retail','NASDAQ'],
  // ── Consumer Staples ───────────────────────────────────────────────────
  ['PG','Procter & Gamble Co.','Consumer Staples','Household & Personal Products','NYSE'],
  ['KO','The Coca-Cola Co.','Consumer Staples','Beverages—Non-Alcoholic','NYSE'],
  ['PEP','PepsiCo Inc.','Consumer Staples','Beverages—Non-Alcoholic','NASDAQ'],
  ['PM','Philip Morris International','Consumer Staples','Tobacco','NYSE'],
  ['MO','Altria Group Inc.','Consumer Staples','Tobacco','NYSE'],
  ['MDLZ','Mondelez International','Consumer Staples','Confectioners','NASDAQ'],
  ['KHC','Kraft Heinz Co.','Consumer Staples','Packaged Foods','NASDAQ'],
  ['WMT','Walmart Inc.','Consumer Staples','Discount Stores','NYSE'],
  ['COST','Costco Wholesale Corp.','Consumer Staples','Discount Stores','NASDAQ'],
  ['TGT','Target Corp.','Consumer Staples','Discount Stores','NYSE'],
  ['KR','The Kroger Co.','Consumer Staples','Grocery Stores','NYSE'],
  ['SYY','Sysco Corp.','Consumer Staples','Food Distribution','NYSE'],
  ['ADM','Archer-Daniels-Midland Co.','Consumer Staples','Farm Products','NYSE'],
  ['GIS','General Mills Inc.','Consumer Staples','Packaged Foods','NYSE'],
  ['HRL','Hormel Foods Corp.','Consumer Staples','Packaged Foods','NYSE'],
  ['K','Kellanova','Consumer Staples','Packaged Foods','NYSE'],
  ['MKC','McCormick & Company','Consumer Staples','Packaged Foods','NYSE'],
  ['STZ','Constellation Brands','Consumer Staples','Beverages—Alcoholic','NYSE'],
  ['TSN','Tyson Foods Inc.','Consumer Staples','Packaged Foods','NYSE'],
  ['CL','Colgate-Palmolive Co.','Consumer Staples','Household & Personal Products','NYSE'],
  ['CLX','The Clorox Co.','Consumer Staples','Household & Personal Products','NYSE'],
  ['EL','Estee Lauder Companies','Consumer Staples','Household & Personal Products','NYSE'],
  ['HSY','The Hershey Co.','Consumer Staples','Confectioners','NYSE'],
  ['MNST','Monster Beverage Corp.','Consumer Staples','Beverages—Non-Alcoholic','NASDAQ'],
  ['KDP','Keurig Dr Pepper Inc.','Consumer Staples','Beverages—Non-Alcoholic','NASDAQ'],
  ['WBA','Walgreens Boots Alliance','Consumer Staples','Pharmaceutical Retailers','NASDAQ'],
  // ── Healthcare ─────────────────────────────────────────────────────────
  ['JNJ','Johnson & Johnson','Healthcare','Drug Manufacturers','NYSE'],
  ['UNH','UnitedHealth Group','Healthcare','Healthcare Plans','NYSE'],
  ['LLY','Eli Lilly and Co.','Healthcare','Drug Manufacturers','NYSE'],
  ['ABBV','AbbVie Inc.','Healthcare','Drug Manufacturers','NYSE'],
  ['PFE','Pfizer Inc.','Healthcare','Drug Manufacturers','NYSE'],
  ['TMO','Thermo Fisher Scientific','Healthcare','Diagnostics & Research','NYSE'],
  ['ABT','Abbott Laboratories','Healthcare','Medical Devices','NYSE'],
  ['DHR','Danaher Corp.','Healthcare','Diagnostics & Research','NYSE'],
  ['CVS','CVS Health Corp.','Healthcare','Healthcare Plans','NYSE'],
  ['CI','The Cigna Group','Healthcare','Healthcare Plans','NYSE'],
  ['BMY','Bristol-Myers Squibb Co.','Healthcare','Drug Manufacturers','NYSE'],
  ['AMGN','Amgen Inc.','Healthcare','Drug Manufacturers','NASDAQ'],
  ['GILD','Gilead Sciences Inc.','Healthcare','Drug Manufacturers','NASDAQ'],
  ['ISRG','Intuitive Surgical Inc.','Healthcare','Medical Devices','NASDAQ'],
  ['VRTX','Vertex Pharmaceuticals','Healthcare','Biotechnology','NASDAQ'],
  ['REGN','Regeneron Pharmaceuticals','Healthcare','Biotechnology','NASDAQ'],
  ['BIIB','Biogen Inc.','Healthcare','Biotechnology','NASDAQ'],
  ['ILMN','Illumina Inc.','Healthcare','Diagnostics & Research','NASDAQ'],
  ['MRNA','Moderna Inc.','Healthcare','Biotechnology','NASDAQ'],
  ['DXCM','DexCom Inc.','Healthcare','Medical Devices','NASDAQ'],
  ['IQV','IQVIA Holdings','Healthcare','Diagnostics & Research','NYSE'],
  ['MDT','Medtronic PLC','Healthcare','Medical Devices','NYSE'],
  ['BSX','Boston Scientific Corp.','Healthcare','Medical Devices','NYSE'],
  ['EW','Edwards Lifesciences','Healthcare','Medical Devices','NYSE'],
  ['SYK','Stryker Corp.','Healthcare','Medical Devices','NYSE'],
  ['ZTS','Zoetis Inc.','Healthcare','Drug Manufacturers','NYSE'],
  ['HCA','HCA Healthcare Inc.','Healthcare','Medical Care Facilities','NYSE'],
  ['CNC','Centene Corp.','Healthcare','Healthcare Plans','NYSE'],
  ['HUM','Humana Inc.','Healthcare','Healthcare Plans','NYSE'],
  ['ELV','Elevance Health Inc.','Healthcare','Healthcare Plans','NYSE'],
  ['MOH','Molina Healthcare','Healthcare','Healthcare Plans','NYSE'],
  ['IDXX','IDEXX Laboratories','Healthcare','Diagnostics & Research','NASDAQ'],
  ['GEHC','GE HealthCare Technologies','Healthcare','Medical Devices','NASDAQ'],
  ['RMD','ResMed Inc.','Healthcare','Medical Devices','NYSE'],
  ['PODD','Insulet Corp.','Healthcare','Medical Devices','NASDAQ'],
  ['BAX','Baxter International','Healthcare','Medical Devices','NYSE'],
  ['BDX','Becton Dickinson','Healthcare','Medical Devices','NYSE'],
  ['COO','The Cooper Companies','Healthcare','Medical Devices','NYSE'],
  ['HOLX','Hologic Inc.','Healthcare','Medical Devices','NASDAQ'],
  ['HSIC','Henry Schein Inc.','Healthcare','Medical Distribution','NASDAQ'],
  ['MTD','Mettler-Toledo International','Healthcare','Diagnostics & Research','NYSE'],
  ['WAT','Waters Corp.','Healthcare','Diagnostics & Research','NYSE'],
  ['ALGN','Align Technology','Healthcare','Medical Devices','NASDAQ'],
  ['ZBH','Zimmer Biomet Holdings','Healthcare','Medical Devices','NYSE'],
  // ── Financials ─────────────────────────────────────────────────────────
  ['BRK-B','Berkshire Hathaway Class B','Financials','Insurance—Diversified','NYSE'],
  ['JPM','JPMorgan Chase & Co.','Financials','Banks—Diversified','NYSE'],
  ['BAC','Bank of America Corp.','Financials','Banks—Diversified','NYSE'],
  ['WFC','Wells Fargo & Co.','Financials','Banks—Diversified','NYSE'],
  ['GS','The Goldman Sachs Group','Financials','Capital Markets','NYSE'],
  ['MS','Morgan Stanley','Financials','Capital Markets','NYSE'],
  ['C','Citigroup Inc.','Financials','Banks—Diversified','NYSE'],
  ['BLK','BlackRock Inc.','Financials','Asset Management','NYSE'],
  ['SCHW','Charles Schwab Corp.','Financials','Capital Markets','NYSE'],
  ['AXP','American Express Co.','Financials','Credit Services','NYSE'],
  ['V','Visa Inc.','Financials','Credit Services','NYSE'],
  ['MA','Mastercard Inc.','Financials','Credit Services','NYSE'],
  ['COF','Capital One Financial','Financials','Credit Services','NYSE'],
  ['USB','U.S. Bancorp','Financials','Banks—Regional','NYSE'],
  ['PNC','PNC Financial Services','Financials','Banks—Regional','NYSE'],
  ['TFC','Truist Financial Corp.','Financials','Banks—Regional','NYSE'],
  ['BK','Bank of New York Mellon','Financials','Banks—Diversified','NYSE'],
  ['STT','State Street Corp.','Financials','Asset Management','NYSE'],
  ['TROW','T. Rowe Price Group','Financials','Asset Management','NASDAQ'],
  ['PRU','Prudential Financial','Financials','Insurance—Life','NYSE'],
  ['MET','MetLife Inc.','Financials','Insurance—Life','NYSE'],
  ['AMP','Ameriprise Financial','Financials','Asset Management','NYSE'],
  ['CB','Chubb Ltd.','Financials','Insurance—Property & Casualty','NYSE'],
  ['ALL','The Allstate Corp.','Financials','Insurance—Property & Casualty','NYSE'],
  ['PGR','The Progressive Corp.','Financials','Insurance—Property & Casualty','NYSE'],
  ['AFL','Aflac Inc.','Financials','Insurance—Life','NYSE'],
  ['TRV','The Travelers Companies','Financials','Insurance—Property & Casualty','NYSE'],
  ['MMC','Marsh & McLennan Companies','Financials','Insurance Brokers','NYSE'],
  ['AJG','Arthur J. Gallagher & Co.','Financials','Insurance Brokers','NYSE'],
  ['AON','Aon PLC','Financials','Insurance Brokers','NYSE'],
  ['DFS','Discover Financial Services','Financials','Credit Services','NYSE'],
  ['SYF','Synchrony Financial','Financials','Credit Services','NYSE'],
  ['PYPL','PayPal Holdings Inc.','Financials','Credit Services','NASDAQ'],
  ['ICE','Intercontinental Exchange','Financials','Financial Data & Stock Exchanges','NYSE'],
  ['CME','CME Group Inc.','Financials','Financial Data & Stock Exchanges','NASDAQ'],
  ['SPGI','S&P Global Inc.','Financials','Financial Data & Stock Exchanges','NYSE'],
  ['MCO','Moody\'s Corp.','Financials','Financial Data & Stock Exchanges','NYSE'],
  ['MSCI','MSCI Inc.','Financials','Financial Data & Stock Exchanges','NYSE'],
  // ── Industrials ────────────────────────────────────────────────────────
  ['GE','GE Aerospace','Industrials','Aerospace & Defense','NYSE'],
  ['HON','Honeywell International','Industrials','Diversified Industrials','NASDAQ'],
  ['RTX','RTX Corp.','Industrials','Aerospace & Defense','NYSE'],
  ['LMT','Lockheed Martin Corp.','Industrials','Aerospace & Defense','NYSE'],
  ['BA','The Boeing Co.','Industrials','Aerospace & Defense','NYSE'],
  ['NOC','Northrop Grumman Corp.','Industrials','Aerospace & Defense','NYSE'],
  ['GD','General Dynamics Corp.','Industrials','Aerospace & Defense','NYSE'],
  ['LHX','L3Harris Technologies','Industrials','Aerospace & Defense','NYSE'],
  ['TXT','Textron Inc.','Industrials','Aerospace & Defense','NYSE'],
  ['HWM','Howmet Aerospace Inc.','Industrials','Aerospace & Defense','NYSE'],
  ['CAT','Caterpillar Inc.','Industrials','Farm & Heavy Construction Machinery','NYSE'],
  ['DE','Deere & Company','Industrials','Farm & Heavy Construction Machinery','NYSE'],
  ['EMR','Emerson Electric Co.','Industrials','Diversified Industrials','NYSE'],
  ['ETN','Eaton Corp. PLC','Industrials','Diversified Industrials','NYSE'],
  ['AME','AMETEK Inc.','Industrials','Diversified Industrials','NYSE'],
  ['PH','Parker-Hannifin Corp.','Industrials','Diversified Industrials','NYSE'],
  ['ROK','Rockwell Automation','Industrials','Specialty Industrial Machinery','NYSE'],
  ['ROP','Roper Technologies','Industrials','Diversified Industrials','NASDAQ'],
  ['FTV','Fortive Corp.','Industrials','Diversified Industrials','NYSE'],
  ['IR','Ingersoll Rand Inc.','Industrials','Specialty Industrial Machinery','NYSE'],
  ['ITW','Illinois Tool Works','Industrials','Diversified Industrials','NYSE'],
  ['DOV','Dover Corp.','Industrials','Diversified Industrials','NYSE'],
  ['IEX','IDEX Corp.','Industrials','Specialty Industrial Machinery','NYSE'],
  ['CTAS','Cintas Corp.','Industrials','Specialty Business Services','NASDAQ'],
  ['VRSK','Verisk Analytics','Industrials','Consulting Services','NASDAQ'],
  ['PCAR','PACCAR Inc.','Industrials','Farm & Heavy Construction Machinery','NASDAQ'],
  ['FAST','Fastenal Co.','Industrials','Industrial Distribution','NASDAQ'],
  ['ODFL','Old Dominion Freight Line','Industrials','Trucking','NASDAQ'],
  ['CPRT','Copart Inc.','Industrials','Specialty Retail','NASDAQ'],
  ['UPS','United Parcel Service','Industrials','Integrated Freight & Logistics','NYSE'],
  ['FDX','FedEx Corp.','Industrials','Integrated Freight & Logistics','NYSE'],
  ['CSX','CSX Corp.','Industrials','Railroads','NASDAQ'],
  ['NSC','Norfolk Southern Corp.','Industrials','Railroads','NYSE'],
  ['UNP','Union Pacific Corp.','Industrials','Railroads','NYSE'],
  ['DAL','Delta Air Lines','Industrials','Airlines','NYSE'],
  ['LUV','Southwest Airlines Co.','Industrials','Airlines','NYSE'],
  ['UAL','United Airlines Holdings','Industrials','Airlines','NASDAQ'],
  ['AAL','American Airlines Group','Industrials','Airlines','NASDAQ'],
  ['WM','Waste Management Inc.','Industrials','Waste Management','NYSE'],
  ['RSG','Republic Services Inc.','Industrials','Waste Management','NYSE'],
  ['EXPD','Expeditors International','Industrials','Integrated Freight & Logistics','NASDAQ'],
  ['CHRW','C.H. Robinson Worldwide','Industrials','Integrated Freight & Logistics','NASDAQ'],
  ['XPO','XPO Inc.','Industrials','Trucking','NYSE'],
  ['JBHT','J.B. Hunt Transport Services','Industrials','Trucking','NASDAQ'],
  ['GWW','W.W. Grainger Inc.','Industrials','Industrial Distribution','NYSE'],
  ['SNA','Snap-on Inc.','Industrials','Tools & Accessories','NYSE'],
  ['SWK','Stanley Black & Decker','Industrials','Tools & Accessories','NYSE'],
  ['MAS','Masco Corp.','Industrials','Building Products & Equipment','NYSE'],
  ['TT','Trane Technologies PLC','Industrials','Specialty Industrial Machinery','NYSE'],
  ['XYL','Xylem Inc.','Industrials','Specialty Industrial Machinery','NYSE'],
  ['WAB','Westinghouse Air Brake Technologies','Industrials','Railroads','NYSE'],
  ['LDOS','Leidos Holdings','Industrials','Defense','NYSE'],
  // ── Energy ─────────────────────────────────────────────────────────────
  ['XOM','Exxon Mobil Corp.','Energy','Oil & Gas Integrated','NYSE'],
  ['CVX','Chevron Corp.','Energy','Oil & Gas Integrated','NYSE'],
  ['COP','ConocoPhillips','Energy','Oil & Gas E&P','NYSE'],
  ['EOG','EOG Resources Inc.','Energy','Oil & Gas E&P','NYSE'],
  ['SLB','SLB (Schlumberger)','Energy','Oil & Gas Equipment & Services','NYSE'],
  ['PSX','Phillips 66','Energy','Oil & Gas Refining & Marketing','NYSE'],
  ['VLO','Valero Energy Corp.','Energy','Oil & Gas Refining & Marketing','NYSE'],
  ['MPC','Marathon Petroleum Corp.','Energy','Oil & Gas Refining & Marketing','NYSE'],
  ['OXY','Occidental Petroleum Corp.','Energy','Oil & Gas E&P','NYSE'],
  ['HAL','Halliburton Co.','Energy','Oil & Gas Equipment & Services','NYSE'],
  ['BKR','Baker Hughes Co.','Energy','Oil & Gas Equipment & Services','NASDAQ'],
  ['DVN','Devon Energy Corp.','Energy','Oil & Gas E&P','NYSE'],
  ['FANG','Diamondback Energy','Energy','Oil & Gas E&P','NASDAQ'],
  ['HES','Hess Corp.','Energy','Oil & Gas Integrated','NYSE'],
  ['EQT','EQT Corp.','Energy','Oil & Gas E&P','NYSE'],
  ['APA','APA Corp.','Energy','Oil & Gas E&P','NASDAQ'],
  ['MRO','Marathon Oil Corp.','Energy','Oil & Gas E&P','NYSE'],
  ['KMI','Kinder Morgan Inc.','Energy','Oil & Gas Midstream','NYSE'],
  ['WMB','Williams Companies','Energy','Oil & Gas Midstream','NYSE'],
  ['OKE','ONEOK Inc.','Energy','Oil & Gas Midstream','NYSE'],
  ['TRGP','Targa Resources Corp.','Energy','Oil & Gas Midstream','NYSE'],
  ['LNG','Cheniere Energy Inc.','Energy','Oil & Gas Midstream','NYSE'],
  // ── Materials ──────────────────────────────────────────────────────────
  ['LIN','Linde PLC','Materials','Specialty Chemicals','NYSE'],
  ['APD','Air Products and Chemicals','Materials','Specialty Chemicals','NYSE'],
  ['ECL','Ecolab Inc.','Materials','Specialty Chemicals','NYSE'],
  ['SHW','The Sherwin-Williams Co.','Materials','Specialty Chemicals','NYSE'],
  ['PPG','PPG Industries Inc.','Materials','Specialty Chemicals','NYSE'],
  ['DOW','Dow Inc.','Materials','Commodity Chemicals','NYSE'],
  ['DD','DuPont de Nemours Inc.','Materials','Specialty Chemicals','NYSE'],
  ['LYB','LyondellBasell Industries','Materials','Commodity Chemicals','NYSE'],
  ['FCX','Freeport-McMoRan Inc.','Materials','Copper','NYSE'],
  ['NEM','Newmont Corp.','Materials','Gold','NYSE'],
  ['NUE','Nucor Corp.','Materials','Steel','NYSE'],
  ['STLD','Steel Dynamics Inc.','Materials','Steel','NASDAQ'],
  ['ALB','Albemarle Corp.','Materials','Specialty Chemicals','NYSE'],
  ['IFF','International Flavors & Fragrances','Materials','Specialty Chemicals','NYSE'],
  ['CF','CF Industries Holdings','Materials','Agricultural Inputs','NYSE'],
  ['MOS','The Mosaic Co.','Materials','Agricultural Inputs','NYSE'],
  ['PKG','Packaging Corp. of America','Materials','Packaging & Containers','NYSE'],
  ['IP','International Paper Co.','Materials','Paper & Paper Products','NYSE'],
  ['WRK','WestRock Co.','Materials','Packaging & Containers','NYSE'],
  // ── Real Estate ────────────────────────────────────────────────────────
  ['AMT','American Tower Corp.','Real Estate','REIT—Specialty','NYSE'],
  ['PLD','Prologis Inc.','Real Estate','REIT—Industrial','NYSE'],
  ['CCI','Crown Castle Inc.','Real Estate','REIT—Specialty','NYSE'],
  ['EQIX','Equinix Inc.','Real Estate','REIT—Specialty','NASDAQ'],
  ['PSA','Public Storage','Real Estate','REIT—Industrial','NYSE'],
  ['SPG','Simon Property Group','Real Estate','REIT—Retail','NYSE'],
  ['O','Realty Income Corp.','Real Estate','REIT—Retail','NYSE'],
  ['WELL','Welltower Inc.','Real Estate','REIT—Healthcare Facilities','NYSE'],
  ['VICI','VICI Properties Inc.','Real Estate','REIT—Diversified','NYSE'],
  ['BXP','BXP Inc.','Real Estate','REIT—Office','NYSE'],
  ['EQR','Equity Residential','Real Estate','REIT—Residential','NYSE'],
  ['AVB','AvalonBay Communities','Real Estate','REIT—Residential','NYSE'],
  ['EXR','Extra Space Storage','Real Estate','REIT—Industrial','NYSE'],
  ['MAA','Mid-America Apartment Communities','Real Estate','REIT—Residential','NYSE'],
  ['ARE','Alexandria Real Estate Equities','Real Estate','REIT—Office','NYSE'],
  ['VTR','Ventas Inc.','Real Estate','REIT—Healthcare Facilities','NYSE'],
  ['NNN','NNN REIT Inc.','Real Estate','REIT—Retail','NYSE'],
  ['KIM','Kimco Realty Corp.','Real Estate','REIT—Retail','NYSE'],
  ['REG','Regency Centers Corp.','Real Estate','REIT—Retail','NASDAQ'],
  // ── Utilities ──────────────────────────────────────────────────────────
  ['NEE','NextEra Energy Inc.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['DUK','Duke Energy Corp.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['SO','Southern Co.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['D','Dominion Energy Inc.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['EXC','Exelon Corp.','Utilities','Utilities—Regulated Electric','NASDAQ'],
  ['SRE','Sempra Energy','Utilities','Utilities—Regulated Electric','NYSE'],
  ['AEP','American Electric Power','Utilities','Utilities—Regulated Electric','NASDAQ'],
  ['XEL','Xcel Energy Inc.','Utilities','Utilities—Regulated Electric','NASDAQ'],
  ['ED','Consolidated Edison','Utilities','Utilities—Regulated Electric','NYSE'],
  ['EIX','Edison International','Utilities','Utilities—Regulated Electric','NYSE'],
  ['ES','Eversource Energy','Utilities','Utilities—Regulated Electric','NYSE'],
  ['FE','FirstEnergy Corp.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['ETR','Entergy Corp.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['AES','The AES Corp.','Utilities','Utilities—Diversified','NYSE'],
  ['AWK','American Water Works','Utilities','Utilities—Regulated Water','NYSE'],
  ['PCG','PG&E Corp.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['NRG','NRG Energy Inc.','Utilities','Utilities—Independent Power Producers','NYSE'],
  ['CMS','CMS Energy Corp.','Utilities','Utilities—Regulated Electric','NYSE'],
  ['CNP','CenterPoint Energy','Utilities','Utilities—Regulated Gas','NYSE'],
  ['NI','NiSource Inc.','Utilities','Utilities—Regulated Gas','NYSE'],
  ['LNT','Alliant Energy Corp.','Utilities','Utilities—Regulated Electric','NASDAQ'],
  ['EVRG','Evergy Inc.','Utilities','Utilities—Regulated Electric','NASDAQ'],
  ['ATO','Atmos Energy Corp.','Utilities','Utilities—Regulated Gas','NYSE'],
  ['PNW','Pinnacle West Capital','Utilities','Utilities—Regulated Electric','NASDAQ'],
  ['OGE','OGE Energy Corp.','Utilities','Utilities—Regulated Electric','NYSE'],
];

export const SP500: StockEntry[] = rows.map(([ticker, name, sector, industry, exchange]) => ({
  ticker, name, sector, industry, exchange,
}));
